- hosts: oci-instances
  vars:
    certbot_install_method: package
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_admin_email: "{{ email }}"
    certbot_certs:
      - domains:
          - "{{ duckdns_subdomain }}.duckdns.org"
    certbot_create_command: "{{ certbot_script }} certonly --non-interactive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }} --preferred-challenges dns --authenticator dns-duckdns --dns-duckdns-token {{ cert_secrets.duckdns_token }} --dns-duckdns-propagation-seconds 60"
    certbot_create_if_missing: true
    # defaults file for duckdns
    duckdns_project_root: /etc/duckdns
    duckdns_project_log: /var/log/duckdns
    # DuckDNS local machine settings
    duckdns_user: duckdns
    duckdns_group: duckdns
    # DuckDNS remote settings
    duckdns_subdomain: "{{ duckdns_subdomain }}"
    duckdns_token: "{{ duckdns_token }}"
    # DuckDNS immediate update
    duckdns_update_now: yes

  pre_tasks:    
    - name: Install python3-pip
      apt:
        name: python3-pip
      become: true
    - name: Install certbot_dns_duckdns
      pip:
        name: certbot_dns_duckdns
      become: true

  roles:
    - role: rofrantz.duckdns
      become: true
    - role: geerlingguy.certbot
      become: true